name: GenerateCV
on:
  push:
    branches: [main]
jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        id: version
        run: echo "version=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Print version
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: echo $VERSION
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate CV
        run: docker-compose up --build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.pdf"
          bodyFile: "CHANGELOG.MD"
          allowUpdates: "true"
          commit: "main"
          tag: ${{ steps.version.outputs.VERSION }}
